#!/bin/bash

pdflatex tulip.tex
pdflatex tulip.tex
rm -f *-*.pdf *.log *.aux *.out *.snm *.toc *.nav

sftp sonata.byu.edu <<EOF
  cd PDF
  put *.pdf
EOF

#ssh sonata.byu.edu <<EOF1
#mail -s "Tulips Presentation" -a PDF/tulip.pdf luiarthur@gmail.com <<EOF2
#EOF2
#EOF1
